### ISSUE TITLE
Late injection for player

### ISSUE THREAD

**Issue by RagnaromTec** [frengor/LightInjector#1]
I always get this message on every player join : [LightInjector] Late injection for player
Should i be worried about this?

**Comment by frengor** [comment]
It means LightInjector isn't able to inject the player as soon as possible. This will make the injector to lose some packets, so it isn't a problem until your plugin would have wanted to do some work on those packets. Since this shouldn't generally happen, I'd be happy to investigate this a bit further. Which server software are you using?

**Comment by RagnaromTec** [comment]
I tested it with 1.19.1 and the latest paper version. The first time a player joins after server start the message does not appear, but after that it appears with every player join.

**Comment by frengor** [comment]
Are there any errors on the console?

**Comment by RagnaromTec** [comment]
no

**Comment by frengor** [comment]
Which plugins have you installed? Which is your architecture and os? (On Linux you can find the architecture with `uname -m`)

**Comment by RagnaromTec** [comment]
I tested different things now. the error only occurs when the server is running behind a bungeecord (waterfall) proxy.

**Comment by frengor** [comment]
I managed to successfully reproduce the bug, it appears only when behind BungeeCord and on Paper servers. Spigot servers are unaffected.

**Comment by frengor** [comment]
Fixed in 1.0.1
